-- Table: public.carros

-- DROP TABLE IF EXISTS public.carros;

CREATE TABLE IF NOT EXISTS public.carros
(
    id_carro bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ano integer NOT NULL,
    cor character varying(255) COLLATE pg_catalog."default",
    modelo character varying(255) COLLATE pg_catalog."default",
    placa character varying(255) COLLATE pg_ca	talog."default",
    CONSTRAINT carros_pkey PRIMARY KEY (id_carro)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.carros
    OWNER to postgres;

-- Table: public.clientes

-- DROP TABLE IF EXISTS public.clientes;

CREATE TABLE IF NOT EXISTS public.clientes
(
    id_cliente bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cpf character varying(255) COLLATE pg_catalog."default",
    data_nas date,
    email character varying(255) COLLATE pg_catalog."default",
    endereco character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.clientes
    OWNER to postgres;

-- Table: public.reservas

-- DROP TABLE IF EXISTS public.reservas;

CREATE TABLE IF NOT EXISTS public.reservas
(
    id_reserva bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_devolu date,
    data_retirada date,
    local_retirada character varying(255) COLLATE pg_catalog."default",
    id_carro bigint,
    id_cliente bigint,
    CONSTRAINT reservas_pkey PRIMARY KEY (id_reserva),
    CONSTRAINT fk56durwx8n4ia34yjk1n9bmacc FOREIGN KEY (id_carro)
        REFERENCES public.carros (id_carro) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkktcjdrr0rosmuyk9d4mgpbx4l FOREIGN KEY (id_cliente)
        REFERENCES public.clientes (id_cliente) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.reservas
    OWNER to postgres;